stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: my-simple-page
  IMAGE_TAG: latest
  CONTAINER_NAME: my-simple-page-container
  TEST_PORT: 3100

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - echo "Docker image built successfully."

test:
  stage: test
  script:
    - docker run -d -p $TEST_PORT:80 --name $CONTAINER_NAME $IMAGE_NAME:$IMAGE_TAG
      # Spustíme kontejner pro testování na pozadí
    - sleep 5
      # Počkáme, než se kontejner nastartuje
    - curl -s http://localhost:$TEST_PORT | grep "<title>"
      # Zkontrolujeme, že výstup HTML obsahuje <title> (nebo jiný indikátor správného obsahu)
    - docker stop $CONTAINER_NAME
      # Zastavíme kontejner po testu
    - docker rm $CONTAINER_NAME
      # Odstraníme kontejner
    - echo "Test completed successfully."

deploy:
  stage: deploy
  script:
    - docker run -d -p $TEST_PORT:80 --name $CONTAINER_NAME $IMAGE_NAME:$IMAGE_TAG
    - echo "Application deployed successfully on port $TEST_PORT."
