stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: my-simple-page
  IMAGE_TAG: latest
  CONTAINER_NAME: my-simple-page-container

# First job: Docker image build
build-image:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - echo "✅ Docker image built successfully."

# Second job: Code check (e.g., HTML validation)
build-check:
  stage: build
  script:
    - echo "🔍 Performing HTML code check (simulated)"
    - grep "<title>" index.html
    - echo "✅ Code check completed successfully."

# Test job: Runs the container and checks page content
test:
  stage: test
  script:
    - docker run -d -p 3100:80 --name $CONTAINER_NAME $IMAGE_NAME:$IMAGE_TAG
    - sleep 3
    - curl -s http://localhost:3100 | grep "Ceník produktů"
    - echo "✅ Test passed – page loaded correctly."
  after_script:
    - docker stop $CONTAINER_NAME
    - docker rm $CONTAINER_NAME

# Deploy job: Only runs if test succeeds
deploy:
  stage: deploy
  script:
    - docker run -d -p 3100:80 --name $CONTAINER_NAME $IMAGE_NAME:$IMAGE_TAG
    - echo "🚀 Application deployed successfully on port 3100."
